import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { roboto } from "./ui/fonts";
import NavBar from "./ui/navbar";
import { InnerContainer, OuterContainer } from "./ui/container";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <OuterContainer>
          <div className="w-full dark:bg-zinc-900 dark:ring-zinc-300/20" />
        </OuterContainer>

        <div>
          <InnerContainer>
            <NavBar className="pt-6"/>
          </InnerContainer>

          <footer>

          </footer>
        </div>
      </body>
    </html >
  );
}
