import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { roboto } from "./ui/fonts";
import Header from "./ui/header";
import { InnerContainer, OuterContainer } from "./ui/container";
import Footer from "./ui/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased relative flex flex-col min-h-screen`}>
        <OuterContainer className="fixed inset-0 -z-10">
          <div className="border-l-1 border-r-1 border-zinc-700/60 w-full dark:bg-zinc-900 dark:ring-zinc-300/20" />
        </OuterContainer>

        <Header className="pt-6" />

        <div className="flex-1">
          Content
        </div>

        <Footer />
      </body>
    </html >
  );
}
